#!/usr/bin/env bash
# Script that displays information about subdomains

get_subdomain_info() {
    local domain=$1
    local subdomain=$2
    local full="${subdomain}.${domain}"
    local dest
    local record_type

    dest=$(dig +short "${full}")
    record_type=$(dig "${full}" | awk '/ANSWER SECTION:/{getline; print $4}')
    echo "The subdomain ${subdomain} is a ${record_type} record and points to ${dest}"
}

domain=$1
subdomain=$2

if [ -z "$subdomain" ]; then
    for sub in www lb-01 web-01 web-02; do
        get_subdomain_info "$domain" "$sub"
    done
else
    get_subdomain_info "$domain" "$subdomain"
fi
