#!/usr/bin/env bash
# Script that displays information about subdomains

get_subdomain_info() {
    local domain=$1
    local subdomain=$2

    dig "${subdomain}.${domain}" | awk -v subd="$subdomain" '/ANSWER SECTION:/{
        getline
        print "The subdomain " subd " is a " $4 " record and points to " $5
    }'
}

domain=$1
subdomain=$2

if [ -z "$subdomain" ]; then
    for sub in www lb-01 web-01 web-02; do
        get_subdomain_info "$domain" "$sub"
    done
else
    get_subdomain_info "$domain" "$subdomain"
fi
